# Site settings
title: "Łukasz Szmelc Resume"
description: ""

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Łukasz Szmelc"
resume_title:                   "Ruby Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "lszmelc@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+48 691 916 875"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"

# resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I'm a self-taught developer with over 5 years of experience. I specialize in Ruby and Ruby on Rails. I have a soft-spot for beautifully crafted product so I also like to work with frontend where I have experience working with React, Vue, and backbone.js. I've had a chance to work on numerous applications, both legacy and new, where I could learn all kinds of development flows and setups. I also have some experience in both GCP and AWS, Docker and Kubernetes, and am familiar with paradigms of object-oriented programming.</p><p>My preferred way of working is a team managed according to SCRUM methodology with weekly or bi-weekly sprints. I love when the team is able to self-organize and thrive on mutual support delivering the best result.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/szmelc"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/szmelc/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default
